### ISSUE TITLE
AI-FeynmaN

### ISSUE THREAD

**Issue by dcasciotti** [MehdiHmidi523/Ai-Feynman-2#2]
Greetings 
I don't understand where these columns come from in the program(ie names)
<img width="1365" alt="searching for best fit column names" src="https://user-images.githubusercontent.com/335966/126038003-cdf98e6a-699d-45d0-bc9a-70612b5923ab.png">
Thank you
Dave

**Comment by MehdiHmidi523** [comment]
Hi there,

I am glad to be of assistance. If you access the FORTRAN file at line 139 you will hopefully find an answer to your question:
https://github.com/SJ001/AI-Feynman/blob/master/aifeynman/symbolic_regress1.f90

For example the 3rd column corresponds to the operation being done. 
More on that here: https://ai-feynman.readthedocs.io/en/latest/inputformat.html

FYI, I was not involved in the creation of this research project. This blog article was merely done in exploration of their work.


Best regards.

**Comment by dcasciotti** [comment]
Thank you very much your suggestion it completely clarifies my understanding.
I understand that the program creates a mystery file y= a+b+c  -  if I input my data x1,x2,x3 does the y column have to be populated or does AI-Feynman calculates it.
Thanks again for your assistance

**Comment by MehdiHmidi523** [comment]
No worries. Yes that is the general Idea.

**Comment by dcasciotti** [comment]
Hi Sorry to be a bother but this fork from DShapiro includes the y value.
Still confused about needing to include the expected y value or does Ai-Feynman calculates it.

Thanks

**Comment by MehdiHmidi523** [comment]
Do you mean the getY() at the bottom of this link:
https://github.com/dcshapiro/AI-Feynman/blob/master/AI_Feynman_2_0.ipynb

That is the author's experiment with noisy data. There a specific y is created and stored as data in a file only to be given to the network to compare results later and ascertain the network's performance. 

Ultimately, the objective is to find a close enough y for the observations or data you supply. As in through the steps outlined in the paper, the network attempts to supply You with an answer over the provided input.
